name:  sample_pubspec
description:  A sample application
dependencies:
  polymer: ">=0.13.0 < 0.14.0"
  paper_elements: any
  core_elements: any
transformers:
- polymer:
    entry_points: web/index.html